using windows bash instead of sh

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -95,7 +95,6 @@ jobs:
            python-version: '3.x'
            publish: true
            containerImage:
-           dependenciesURL: https://github.com/hypothetical-inc/gafferDependencies/releases/download/0.54.1.0/gafferDependencies-0.54.1.0-windows-msvc2017.zip
            testRunner: cmd
            sconsCacheMegabytes: 400
 
@@ -125,26 +124,26 @@ jobs:
       if: runner.os == 'Windows'
 
 
-    # - name: Install toolchain (MacOS)
-    #   # Prefer `pip install` where possible because it is faster
-    #   # than `brew install`.
-    #   run: |
-    #     pip install scons==3.1.2
-    #     # Ensure scons is on PATH, at some point it vanished, maybe as part of GH Py 2-3 migration?
-    #     echo `pip show scons | grep "Location:" | cut -d ' ' -f2`/../../../bin >> $GITHUB_PATH
-    #     pip install sphinx==1.8.1 sphinx_rtd_theme==0.4.3 recommonmark==0.5.0 docutils==0.12
-    #     # Force inkscape < 1.0 until SConstruct is updated
-    #     brew install --cask xquartz &&
-    #     brew install --cask ./config/brew/Casks/inkscape.rb
-    #   if: runner.os == 'macOS'
-    #
-    # - name: Install toolchain (Linux)
-    #   run: |
-    #     echo /opt/rh/devtoolset-6/root/bin >> $GITHUB_PATH
-    #     Xvfb :99 -screen 0 1280x1024x24 &
-    #     metacity&
-    #     useradd -m testUser
-    #   if: runner.os == 'Linux'
+    - name: Install toolchain (MacOS)
+      # Prefer `pip install` where possible because it is faster
+      # than `brew install`.
+      run: |
+        pip install scons==3.1.2
+        # Ensure scons is on PATH, at some point it vanished, maybe as part of GH Py 2-3 migration?
+        echo `pip show scons | grep "Location:" | cut -d ' ' -f2`/../../../bin >> $GITHUB_PATH
+        pip install sphinx==1.8.1 sphinx_rtd_theme==0.4.3 recommonmark==0.5.0 docutils==0.12
+        # Force inkscape < 1.0 until SConstruct is updated
+        brew install --cask xquartz &&
+        brew install --cask ./config/brew/Casks/inkscape.rb
+      if: runner.os == 'macOS'
+
+    - name: Install toolchain (Linux)
+      run: |
+        echo /opt/rh/devtoolset-6/root/bin >> $GITHUB_PATH
+        Xvfb :99 -screen 0 1280x1024x24 &
+        metacity&
+        useradd -m testUser
+      if: runner.os == 'Linux'
 
     - name: Install toolchain (Windows)
       shell: bash
@@ -236,7 +235,7 @@ jobs:
     - name: Build Gaffer Dependencies
       shell: bash
       run: |
-        ./build.py > build.log 2>&1 || ( tail -n 200 ./build.log ; grep ' error' ./build.log ; exit -1 )
+        (./build.py 2>&1 | tee build.log ) || ( tail -n 200 ./build.log ; grep ' error' ./build.log ; exit -1 )
 
     # - name: Test
     #   run: |
